### ISSUE TITLE
one data sample was gone

### ISSUE THREAD

**Issue by linglingtingfei** [hms-dbmi/UpSetR#124]
Hi,
I input six sample data, but why are there only five samples on the plot, it's weird. I showed that at below picture, the sample data "cf_leaf=Chiifu_leaf$chiifu_leaf" was gone. I tried it many times.

![image](https://user-images.githubusercontent.com/20789616/42857105-0571404a-8a7b-11e8-8c6d-496ef4634339.png)
![2](https://user-images.githubusercontent.com/20789616/42857112-0b66a026-8a7b-11e8-9907-b9cbad4c6787.png)

**Comment by akaEmma** [comment]
Does cf_leaf=Chiifu_leaf$chiifu_leaf have any NAs?

**Comment by JakeConway** [comment]
`nsets` parameter is defaulted to 5. change to `nsets = 6` to include six sets. see `?upset` for details
