### ISSUE TITLE
Set Size Axis cut-off

### ISSUE THREAD

**Issue by RichardCorbett** [hms-dbmi/UpSetR#125]
Hi there.

Noob question here.   I'm making my first upset plots and in some cases the axis labels on the "Set Size" axis are cut off the edge of the produced image.    Is there a way to increase the margin, or otherwise ensure that I get the full "Set Size" axis and labels in my final image?

**Comment by JakeConway** [comment]
I just added a parameter to set the maximum size of set size scale. This may help as an alternative to increasing the size of your image.
