### ISSUE TITLE
query single intersection error 

### ISSUE THREAD

**Issue by RichardCorbett** [hms-dbmi/UpSetR#126]
Hi there,
Following your example online this works as expected:
```
library(UpSetR)
movies <- read.csv(system.file("extdata", "movies.csv", package = "UpSetR"), 
                    header = T, sep = ";")
upset(movies, queries = list(list(query = intersects, params = list("Drama"), active = T)))
```

However, when using my own data I get an error:
```
D = c(`A` = 3626818, `B` = 1652, `C` = 153154, `A&B` = 1620, `A&C` = 64098, `B&C` = 13399, `A&B&C` = 28446)
upset(fromExpression(D), queries = list(list(query = intersects, params = list("A"),active = T)))
```
**Error** :  Error in FUN(X[[i]], ...) : object 'freq' not found

When I switch my query to use an intersection of multiple sets, it works!
```
D = c(`A` = 3626818, `B` = 1652, `C` = 153154, `A&B` = 1620, `A&C` = 64098, `B&C` = 13399, `A&B&C` = 28446)
upset(fromExpression(D), queries = list(list(query = intersects, params = list("A", "B"),active = T)))
```

How can I highlight a set that is unique from the other sets?  ie. how can I highlight "A"?

**Comment by JakeConway** [comment]
Hello Richard,

That bug is fixed in our development version. You can get it using `devtools::install_github("hms-dbmi/UpSetR")`. We should be submitting an updated version of the package to CRAN soon.

- Jake

**Comment by RichardCorbett** [comment]
Thanks Jake,

I tried updating, but now get this new error:
```
> D = c(`A` = 3626818, `B` = 1652, `C` = 153154, `A&B` = 1620, `A&C` = 64098, `B&C` = 13399, `A&B&C` = 28446)
> upset(fromExpression(D), queries = list(list(query = intersects, params = list("A", "B"),active = T)))

```Error in grid.newpage() : could not find function "grid.newpage"

**Comment by RichardCorbett** [comment]
Dang, I hit the close button by accident.  Apologies!

**Comment by JakeConway** [comment]
Hello Richard,

This has been fixed in the development version. For the latest version download the package using `devtools::install_github("hms-dbmi/UpSetR")`
