### ISSUE TITLE
Upset Plot with Mupltiple CSV"s

### ISSUE THREAD

**Issue by waqarali141** [hms-dbmi/UpSetR#131]
Hi am a newbie to R, I have to plot a upset graph against my data. 

i have 3 csvs, say A,B and C.

All the files contain only one column say ph#. 

i want to plot a upset plot for A,B and C on column ph#. Any idea how would i do that with R ??

**Comment by RichardJActon** [comment]
Hi @waqarali141 

    A <- unlist(read.csv("A.txt",stringsAsFactors = FALSE,header = TRUE),use.names = FALSE)
    B <- unlist(read.csv("B.txt",stringsAsFactors = FALSE,header = TRUE),use.names = FALSE)
    C <- unlist(read.csv("C.txt",stringsAsFactors = FALSE,header = TRUE),use.names = FALSE)
    sets <- list(A=A,B=B,C=C)
    upset(fromList(sets),
      sets.bar.color = "grey")

![rplot](https://user-images.githubusercontent.com/6893043/44897980-78e46880-acf5-11e8-9b28-f60c715b382a.png)

**Comment by RichardJActon** [comment]
@waqarali141 if this fixed your problem please close the issue so that the developers can have their attention drawn to unresolved issues.
