### ISSUE TITLE
Possible issue with processing CSV input

### ISSUE THREAD

**Issue by alexpreynolds** [hms-dbmi/UpSetR#142]
This test is modeled off the R vignette posted here, which shows basic usage examples: https://cran.r-project.org/web/packages/UpSetR/vignettes/basic.usage.html

I am starting with the following CSV (`publication-detail.upsetR.csv.zip`):

[publication-detail.upsetR.csv.zip](https://github.com/hms-dbmi/UpSetR/files/2646574/publication-detail.upsetR.csv.zip)

This is a binary matrix representing six categories of data. Like the "movies" example dataset, it is a CSV file using a semi-colon as a field delimiter.

I then run this CSV file through the following script:

```
#!/usr/bin/env Rscript

args = commandArgs(trailingOnly=TRUE)
if (length(args)!=2) {
   print(args)
   stop("Two arguments must be supplied.n", call.=FALSE)
}

library(UpSetR)
d <- read.csv(args[1], header=T, sep=';')
pdf(args[2], onefile=F)
upset(d,
      sets = c("maurano-2012", "maurano-2015", "roadmap", "sterg", "thurman", "unpublished"),
      order.by = "freq",
      sets.x.label = "Total publication count",
      mainbar.y.label = "Publication subset count",
      text.scale = c(1.3, 1.3, 1, 1, 2, 0.75))
dev.off()
```

For example:

```
$ ./plot.Rscript publication-detail.upsetR.csv publication-detail.upsetR.csv.pdf
```

I get the following error:

```
Error in `[.data.frame`(data, sets) : undefined columns selected
Calls: upset ... order_sets -> colSums -> is.data.frame -> [ -> [.data.frame
Execution halted
```

If I modify the script to specify a number of sets (`nsets`), instead of the names of the desired columns (`sets`), then the script appears to work correctly:

```
upset(d,
      nsets = 6,
      order.by = "freq",
      sets.x.label = "Total publication count",
      mainbar.y.label = "Publication subset count",
      text.scale = c(1.3, 1.3, 1, 1, 2, 0.75))
```

("Working correctly" here means all six categories are shown in the plot.)

However, if I leave out both the `nsets` and `sets` parameters, then the plot is missing one of the six categories:

```
upset(d,
      order.by = "freq",
      sets.x.label = "Total publication count",
      mainbar.y.label = "Publication subset count",
      text.scale = c(1.3, 1.3, 1, 1, 2, 0.75))
```

Specifically, the resulting plot is missing data and subset memberships from the `sterg` column. This, too, is incorrect behavior.

**Comment by JakeConway** [comment]
when R reads in a file, the dashes in column names are converted to periods. Include check.names parameter in read.csv

`d <- read.csv(args[1], header=T, sep=';', check.names = FALSE)`
