### ISSUE TITLE
Plotting with big numbers

### ISSUE THREAD

**Issue by aderzelle** [hms-dbmi/UpSetR#157]
Hello,

I have a data set which leads to intersection set of really big size. This creates a problem in the plot because the numbers are bog and therefore they overlap each other. 
I tried to change their angle but that doesn't solve the problem, even at a 90° angle because then the number overlap with the neighbouring bars or with the x axis.
Is there a way to reduce their font? 
Or more generally, what's the preferred way to deal with this situation? 

Thanks a lot.

**Comment by JakeConway** [comment]
1) You could use `text.scale` to scale the size of text
2) You could apply log, log2 or log10 transforms to the intersection sizes using `scale.intersections`
