### ISSUE TITLE
IS THIS PROJECT DEAD?

### ISSUE THREAD

**Issue by diplodata** [hms-dbmi/UpSetR#159]
Sorry for shouting, but I think it needs to stand out!

**Comment by EarlGlynn** [comment]
CRAN shows latest version is 1.3.3 from over two years ago:  2017-03-21.  Would be nice to have new features, like set_size.show, from version 1.4 on CRAN by now.

**Comment by JakeConway** [comment]
Just uploaded to CRAN

**Comment by diplodata** [comment]
Sorry the issue isn't about v1.4 but whether this project is still under development. The v1.4 commits are 10 months alo.
