### ISSUE TITLE
Misleading map when nsets < named sets

### ISSUE THREAD

**Issue by cellocgw** [hms-dbmi/UpSetR#160]
Consider this example:
run1 = c('LRE&SL' = 55, 'LFE&SL' = 1, 'LRE&LOE' = 13, 'SL&LM'= 1, 'LOE&DO'= 1)
I understand that upset defaults to nsets = 5.  The problem is that when I run upset with this input, the graph and the intersection links misleadingly suggest that "SL" has a single non-intersecting element. 
There should be some validity check which refuses to plot only "half" of an intersection when one of the sets in question is not otherwise plotted (i.e. "LFE" in this case. )
![shortset](https://user-images.githubusercontent.com/8104153/57246280-deb68c00-700a-11e9-9b7b-2a73d2670c31.png

**Comment by asusete** [comment]
I have a similar problem :
The names of my sets are "Set1> Set2", "Set1> Set3", "Set2> Set3". 
When I make an upset with empty.intersections = "on", they appear in "Set1...Set2", "Set1...Set3", "Set2...Set3" and without empty.intersections, they are correctly display "Set1> Set2", "Set1> Set3", "Set2> Set3" ?

**Comment by JakeConway** [comment]
@cellocgw this is because when nsets is less than number of sets, it is blinded to the fact that other sets exist.

@asusete this is because R doesn't like spaces and certain other characters in column names. I will check to see if there is anywhere we arent setting check.names = FALSE when reading data.

**Comment by asusete** [comment]
But it only happen when I use empty.intersections = "on" !
I tried check.names, it doesn't change anything.

**Comment by JakeConway** [comment]
Which version of the R package are you using. I believe this is fixed in 1.4.0 (uploaded to CRAN last week) and the development version on github (can install with `devtools::install_github("hms-dbmi/UpSetR")`)

**Comment by asusete** [comment]
Indeed, the update fixed the problem. Thanks !
