### ISSUE TITLE
New intersection function name

### ISSUE THREAD

**Issue by JakeConway** [hms-dbmi/UpSetR#17]
It appears that R linked both "intersection" and "intersect" with the intersect function help page. What would be a suitable name?

**Comment by ngehlenborg** [comment]
Does the package declare a namespace? http://r-pkgs.had.co.nz/namespace.html

If not, we should declare one (e.g. `upsetr`) and then use a shorter name for the intersection function, e.g. `intersect`, so that it can be used like this `upsetr::intersect(...)`.
