### ISSUE TITLE
use lightgray for non-query data points in built-in attribute plots if queries are present

### ISSUE THREAD

**Issue by ngehlenborg** [hms-dbmi/UpSetR#19]
That would make it easier to see those data points highlighted in the color of the query.

**Comment by JakeConway** [comment]
The user can control the color of the attribute plots that represents all the intersections in the main bars using the att.color parameter. Right now I have it set to whatever color the main bar color is. Should I still change it?

**Comment by ngehlenborg** [comment]
I was wondering if we could make the default color light gray only when there are queries, otherwise it should remain black. Not sure if this is even possible with the mechanism that we have right now for attribute plots.

**Comment by JakeConway** [comment]
Yeah its possible. Should it only be light gray if queries = T when the user hasn't changed the default color. So if they pick a color other than black we wont change it?

**Comment by ngehlenborg** [comment]
Yes, only if queries = T. I would make the color for those built-in attribute plots independent of the color of the main bar.
