### ISSUE TITLE
mb.ratio throws off set size bar vertical alignment

### ISSUE THREAD

**Issue by nweerasu** [hms-dbmi/UpSetR#192]
Modifying mb.ratio to anything other than default causes the vertical alignment of the set size bars to not shift with the label names. It also causes the matrix background layer to overlap the x axis of the bar chart. 

![image](https://user-images.githubusercontent.com/18601221/91468854-9440ca80-e860-11ea-892b-38be56507e25.png)
![image](https://user-images.githubusercontent.com/18601221/91468980-c6522c80-e860-11ea-94a9-8a4d7d4bb43b.png)

**Comment by JakeConway** [comment]
I haven't been able to reproduce this issue. Are you able to provide the code that produced this issue?
