### ISSUE TITLE
What colors are supported by UpSetR?

### ISSUE THREAD

**Issue by CPerscheid** [hms-dbmi/UpSetR#196]
Hi there, 
I wanted to color the set sizes of my plot with randomly selected CSS colors. However, it seems UpsetR can only handle a very limited set of colors, is that correct?
If so, which colors are currently supported? I have seen [issue #7](https://github.com/hms-dbmi/UpSetR/issues/7) about default color palettes, however when I tried to use these I still got the error that (neither the string names nor the hex values) cannot be found by UpSetR.

Any help appreciated.

Best,
Cindy

**Comment by JakeConway** [comment]
UpSetR is built on top of ggplot2, so any colors (or hex codes) should work. Do you have an example of colors/hex codes that aren't working?

**Comment by CPerscheid** [comment]
Hi Jake,
I tried out once again. It turns out that UpSetR does not recognize lists of colors, but is has to be a vector of colors. Casting my list into a vector via `unlist(colors, use.names=FALSE)` then worked fine.

I thought I tried that out before (casting my list into a vector) and it didn't work. Well - seems my head got stuck somewhen somewhere as well... ^^
Nevertheless, thanks a lot!
