### ISSUE TITLE
Does Upset support 6 vector lists?

### ISSUE THREAD

**Issue by mrouard** [hms-dbmi/UpSetR#197]
Hello,

I have tried to make an Upset plot using 6 lists. By first using the online version, it displayed only 5 elements. So I made a test directly with R but the same behaviour occurred. I don't think this is due to my dataset.

with a fake dataset, here is the result

`listInput <- list(one = c(1, 2 ), two = c(1, 2, 3), three = c(1, 2, 3, 4), four = c(1, 2, 3, 4, 5), five = c(1, 2, 3, 4, 5, 6), six = c(1, 2, 3, 4, 5, 6, 7))`
`upset(fromList(listInput), order.by = c("degree"))`

![upset](https://user-images.githubusercontent.com/6577109/103772372-b5dd6a00-5029-11eb-889c-bd61f0f40e91.jpg)

Any idea why?

Thanks in advance for your help

**Comment by JakeConway** [comment]
Yes, just set the `nsets` parameter to the desired number of sets.

**Comment by mrouard** [comment]
It works fine. 👍  Many thanks for the prompt answer.
Maybe the script behind https://gehlenborglab.shinyapps.io/upsetr/ does not use it as well.
