### ISSUE TITLE
Error using own data

### ISSUE THREAD

**Issue by larry1995** [hms-dbmi/UpSetR#213]
Hi,

I am currently learning your UpSetR to do analysis on my own data. However, I encountered this error without a solution. Could you help me figure out what happened? Thank you so much

![image](https://user-images.githubusercontent.com/20786624/121309549-288f9180-c8b7-11eb-99b7-da9192149c97.png)
![image](https://user-images.githubusercontent.com/20786624/121309576-3218f980-c8b7-11eb-9aad-27caa8b060d1.png)

**Comment by JakeConway** [comment]
If you convert TRUE/FALSE to 1/0 it should work
