### ISSUE TITLE
what is the  command of adding percentage for main.bar?

### ISSUE THREAD

**Issue by li0604** [hms-dbmi/UpSetR#216]
Hello,everyone.

I want to add the percentage of main.bar in upsetR, bur I didn't find rhe action command. When I read an example given by https://www.cn-healthcare.com/articlewm/20210609/content-1229907.html  page. I tried the 'Intersection ratio'=intersection_ratio() and it didn't work?

would you mind sharing the script of adding percentage in upsetR for main.bar?

Thanks a lot.

**Comment by krassowski** [comment]
The examples in the linked article are for a different R package.

**Comment by li0604** [comment]
Thanks a lot.
