### ISSUE TITLE
add htmlwidget functionality

### ISSUE THREAD

**Issue by timelyportfolio** [hms-dbmi/UpSetR#25]
I love your work with UpSet, and I had the JavaScript piece on my list to do as an [`htmlwidget`](http://htmlwidgets.org) of the week at [BuildingWidgets](http://buildingwidgets/blog).  I had no idea that you had a `R` package until I just spotted it on the CRAN feed.  I'd love to volunteer to make this into a `htmlwidget` if you would like to pair the interactivity of the JavaScript with the engine of R.

Before `htmlwidgets` existed, I had played a little integrating `UpSet` with `rCharts` http://timelyportfolio.github.io/upset where I added a couple `R` datasets to the list.  The ugly code is in a fork https://github.com/timelyportfolio/upset.

**Comment by ngehlenborg** [comment]
@timelyportfolio: would you use the R version of UpSet to create the widget or would that be based on the interactive version of UpSet (https://github.com/VCG/upset/)?

**Comment by happyshows** [comment]
+1 really cool viz and look forward for the implementation of htmlwidget version.

**Comment by jaeddy** [comment]
+1 (and a vote for something more like ggplot :: plotly analog rather than or before the full interactive version).

**Comment by liutiming** [comment]
What is the status of this issue?
