### ISSUE TITLE
error with UpSetR plot

### ISSUE THREAD

**Issue by AvolaAmg** [hms-dbmi/UpSetR#251]
Hi there, I have a scRNA-seq dataset and I am trying to plot the coexpression frequency of 4 genes and I decided to do this with UpSetR, However I am getting an error and I do not know how to fix it.
I have my dataframe as an .RDS file and this is how it looks 

`head(Neurotransmitter_frequency`
                   VGlut_exp Gad1_exp VAChT_exp Vmat_exp
AAACCCAAGAATTGTG-1         0        0         0        0
AAACCCAAGTAGGAAG-1         0        0         0        0
AAACCCAGTATCAGCT-1         0        0         0        0
AAACCCAGTGGTCTAT-1         0        0         0        0
AAACCCATCACTAGCA-1         1        0         0        0
AAACCCATCGCAGTGC-1         0        0         0        0
`

and this is what I have done for the UpSetR plot

`library(UpSetR)`
`library(ggplot2)`
`Neurotransmitter_frequency` = `readRDS("/lab/Neurotransmitters_frequency.RDS")`
`set_variables<- c("VGlut_exp", "Gad1_exp", "VAChT_exp", "Vmat_exp")`
`upset(Neurotransmitter_frequency, sets = set_variables)`

however I get this error: 

Error in colSums(data[sets]) : 'x' must be numeric

no idea how to fix this, is it because of the row names with the cells ID? 
I am totally stuck, any help will be much welcome :) 

Thanks!

**Comment by JakeConway** [comment]
I would check to make sure that those columns aren't factors. E.g. if you do `Neurotransmitter_frequency$Vmat_exp` does it say it's a factor with levels 0 and 1?
