### ISSUE TITLE
error reading data

### ISSUE THREAD

**Issue by oeco28** [hms-dbmi/UpSetR#32]
Hello Jake,
  I am having an issue when trying a simple intersection with UpSetR. The data is as follows:

Name;Amelonado;Contamana;Criollo;Curaray;Guianna;Iquitos;Maranon;Nacional;Nanay;Purus
Thecc1EG000181;1;0;0;0;0;0;0;0;0;0
Thecc1EG001933;1;0;0;0;0;0;0;0;0;0
Thecc1EG003999;1;0;0;0;0;0;0;0;0;0
Thecc1EG005677;1;0;0;0;0;0;0;0;0;0
Thecc1EG006000;1;0;0;0;0;0;0;0;0;0
.
.
.

I load the data 
> genes <- read.csv("mygenes",header=T,sep=";")

and try upset with:
> upset(genes2, sets = c("Amelonado", "Contamana", "Criollo", "Curaray", "Guianna", "Iquitos", "Maranon", "Nacional", "Nanay", "Purus"), sets.bar.color = "#56B4E9",order.by = "freq", empty.intersections = "on")

I obtain the error:
Error in start_col:end_col : argument of length 0

but I tried comparing with your example sets and I cannot figure out what the potential problem could be.
Has anyone experienced this problem?

thanks
Omar

**Comment by JakeConway** [comment]
Hello Omar.. It is because Amelondado is the only set that contains an element so there is no intersections. I will implement an update that prevents against this error. 

Thanks,
Jake

**Comment by oeco28** [comment]
Hi Jake,
  Sorry, I was not explicit (that is just a snapshot of the data, head of the file). In fact if I load the data into Upset online I get a figure with the intersections. See below. There is something else I cannot figure out. The file loaded to both is the same. I am trying to post the image below, I hope it goes through

![image](https://cloud.githubusercontent.com/assets/14342251/9952804/e103a886-5d8e-11e5-8d2e-4d38918a35b5.png)

**Comment by JakeConway** [comment]
hmmm. strange. can you send me an example data set resembling your data at jake_conway@student.uml.edu
