### ISSUE TITLE
need a way to display specific empty intersections

### ISSUE THREAD

**Issue by leipzig** [hms-dbmi/UpSetR#33]
My matrix looks like this
```
     ensembl_gene_id Heart_Down Heart_Unchanged Heart_Up Muscle_Down Muscle_Unchanged Muscle_Up
1 ENSMUSG00000000001          0               1        0           1                0         0
2 ENSMUSG00000000028          0               1        0           0                1         0
3 ENSMUSG00000000031          0               1        0           0                1         0
4 ENSMUSG00000000056          0               1        0           0                1         0
5 ENSMUSG00000000058          0               1        0           0                1         0
6 ENSMUSG00000000078          0               1        0           0                1         0
...
```
There are 9 meaningful intersections but two of them are empty. Then there are a lot of meaningless intersections. I need a way to display all 9.

**Comment by JakeConway** [comment]
We will add an option to explicitly select certain empty intersections. Thanks for the idea!

**Comment by JakeConway** [comment]
Added new 'intersections' parameter that allows selection of specific intersections to show. An example:
`movies <- read.csv( system.file("extdata", "movies.csv", package = "UpSetR"), header=TRUE, sep=";" )

intersections <- list(list("Drama", "Action", "Comedy"), list("Drama", "Comedy", "Thriller", "Romance"), list("Drama"), list("Comedy"), list("Drama", "Comedy", "Action", "Thriller"), list("Western"))

upset(movies, intersections = intersections)`

**Comment by leipzig** [comment]
Thanks!
