### ISSUE TITLE
allow rotation of bar labels on the intersection bar chart in 45 degree steps

### ISSUE THREAD

**Issue by ngehlenborg** [hms-dbmi/UpSetR#34]
In the plot below the labels at the top of bars are overlapping. There should be an option to rotate them in 45 degree increments.

<img width="1308" alt="unknown" src="https://cloud.githubusercontent.com/assets/1216518/13152988/cf2406f4-d63f-11e5-9520-9699a68e9188.png">

**Comment by JakeConway** [comment]
there is an option. it's called 'number.angles'

**Comment by ngehlenborg** [comment]
Thanks!
