### ISSUE TITLE
Return value?

### ISSUE THREAD

**Issue by jjalcolea** [hms-dbmi/UpSetR#39]
Hi. Thanks for such a great Package!

The problem I'm facing is due to the `upset` function not returning a value, as does `ggplot`, for example. I need to store the plot in a variable to `print` it later in a different context. Is it possible for the `upset` function to return a "printable" plot object?

Best wishes,

Juanje.

**Comment by JakeConway** [comment]
The upset plot is made up of 3 different plots (2 bar, 1 matrix) arranged on a 100 by 100 grid. You will be able to return the grob objects of each if you modify the `upset.R` file to return `c(Main_bar, Matrix, Sizes)`.

Please let me know if this helps!

**Comment by jjalcolea** [comment]
Thanks a lot for your quick answer! I'll try ASAP and let you know...

Best,

Juanje.
