### ISSUE TITLE
grid library not loaded automatically

### ISSUE THREAD

**Issue by eroberson** [hms-dbmi/UpSetR#42]
Using df of values for upset:

```
require( upset )
upset( df )
```

returns the following error: 

> Error in theme(panel.background = element_rect(fill = "white"), plot.margin = unit(c(0.5,  : 
  could not find function "unit"

Fixed by manually loading grid:
```
require( grid )
upset( df )
** plot produced **
```

Session info:

> R version 3.1.1 (2014-07-10)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> 
> locale:
> [1] LC_COLLATE=English_United States.1252 
> [2] LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252
> [4] LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] grid      stats     graphics  grDevices utils     datasets  methods  
> [8] base     
> 
> other attached packages:
>  [1] reshape2_1.4.1 ggplot2_1.0.1  xlsx_0.5.7     xlsxjars_0.6.1 rJava_0.9-7   
>  [6] UpSetR_1.2.0   stringr_1.0.0  magrittr_1.5   dplyr_0.4.1    plyr_1.8.3    
> 
> loaded via a namespace (and not attached):
>  [1] assertthat_0.1   colorspace_1.2-6 DBI_0.3.1        digest_0.6.8    
>  [5] gridExtra_2.0.0  gtable_0.1.2     knitr_1.11       labeling_0.3    
>  [9] lazyeval_0.1.10  MASS_7.3-44      munsell_0.4.2    parallel_3.1.1  
> [13] proto_0.3-10     Rcpp_0.12.1      scales_0.3.0     stringi_0.5-5   
> [17] tools_3.1.1     

```

**Comment by JakeConway** [comment]
We were not able to reproduce this issue
