### ISSUE TITLE
Control font size of y label and tick marks

### ISSUE THREAD

**Issue by topherconley** [hms-dbmi/UpSetR#43]
Nice package! 

The font size of `mainbar.y.label` and the y axis tick marks are too small for my liking. Is it possible to increase their size? Could something like the `name.size` argument be added for these components? The demo figures do not seem to have this problem, but I cannot reproduce the large font size on my local machine.

**Comment by JakeConway** [comment]
I had to decrease the font sizes for the ggplot2 update. Do you have the latest version of ggplot2 installed?

**Comment by ngehlenborg** [comment]
@JakeConway - Maybe we should provide a parameter to pass in fontsizes for any fonts used in the plot. I am wondering if the best solution for this would be via ggplot2 themes?

**Comment by ngehlenborg** [comment]
This is related to #24.

**Comment by natbprice** [comment]
I agree the font size is way too small. Is there any temporary fix to this issue? The plot is nice, but is basically unusable with default font sizes.

**Comment by JakeConway** [comment]
This is now a feature on the github version of the package. Download the github version using `devtools::install_github('hms-dbmi/UpSetR')`, and then refer to Example 2 in the basic usage vignette here: https://github.com/hms-dbmi/UpSetR/blob/master/vignettes/basic.usage.Rmd

This will also be a feature on the shiny application shortly.
