### ISSUE TITLE
Applying metadata to the Matrix

### ISSUE THREAD

**Issue by dbetel** [hms-dbmi/UpSetR#44]
Hi,
I've been trying to apply a simple coloring scheme to the matrix background but i cannot seem to get it to work. Using example 5 from the metadata vignette I identified these two (possibly related) errors:

1. When reversing the order of the metadata `plots` list (i.e. "matrix_row"  before "hist") results in the following error:
`Error in rep_len(1, ncol) : invalid 'length.out' value`

2. When listing only "matrix_row" and no other plot in the `plots` list results in the following error:
`Error in `*tmp*`[[i]] : subscript out of bounds`.

Happy to provide more details if needed. 
Doron Betel <dob2014@med.cornell.edu>

**Comment by JakeConway** [comment]
Hello Doron,

Thanks for the catch! I've just fixed the issue..
You can download the the latest Github code with `devtools::install_github("hms-dbmi/UpSetR")`

I will also be sending the package to CRAN, so it should be available from there by tomorrow
