### ISSUE TITLE
Axis break?

### ISSUE THREAD

**Issue by AndrewLangvt** [hms-dbmi/UpSetR#45]
Hi, loving UpSetR!!  

I'm working on an 8 way comparison, and would like to induce an axis break in the y-axis.  I can't seem to find a way to make this happen in all of the info I've dug through on UpSetR... is there any way to do so? The count of intersections between all 8 sets is 4,000 and next greatest is 800.  This results in some rather small bars after that first big one! 

Alternatively, if this isn't possible, can UpSet log transform the counts?

**Comment by ngehlenborg** [comment]
Andrew - thanks for pointing out this omission! The original UpSet (http://www.caleydo.org/tools/upset/) nicely supports this scenario with breaks and folded bars but we never got around to implementing support for this in UpSetR.

I believe that log transformation is possible but @JakeConway will be able to confirm. We will look into options to add breaks to the y-axis but I am not sure if there is a straightforward solution.

**Comment by AndrewLangvt** [comment]
Great, thanks much!  I've attempted using the original version of UpSet, but it would appear my dataset is too large.  I can input up to ~65500 elements per set, but once I go above that, UpSet seems to get quite upset! :-P I'm working with a dataset that is just shy of 100K elements, so I'm hoping to make the log transformation happen in R if the axis break is not possible!  Appreciate the effort of looking into it, eager to hear the outcome!

**Comment by LRizzardi1** [comment]
Also dealing with a similar issue, but needing y-axis break as one intersection has 10,000 more instances than the others. For same reason need x-axis break for the sets as well.

**Comment by JakeConway** [comment]
There is now options for log2 and log10 scales for both the intersection sizes and set sizes. The latest version of the package is on CRAN now.

**Comment by AndrewLangvt** [comment]
Hi Jake, 

I am putting some final touches on a publication and I want to tweak one of my upset graphs.  Using the same dataset, and the same code, as previously when I successfully generated upset graphs with log10 transformations of the intersection counts- I am now getting the following error:

Error in seq.default(min, max, by = by) : 
  'from' cannot be NA, NaN or infinite

I've checked my dataset several times over and cannot locate any NA, NaN, or inf values.  Any chance something has been altered with Upset in the past few months that would cause an issue with my dataset that was previously a non-issue in terms of the log transformation?

**Comment by JakeConway** [comment]
Hell Andrew,

That bug has been patched in the Github version of the package. We are waiting until the next ggplot2 release to submit an updated version of the package to CRAN. 

You can install the Github version of the package using `devtools::install_github("hms-dbmi/UpSetR")`

**Comment by AndrewLangvt** [comment]
Awesome; thanks so much for the quick reply!

**Comment by AndrewLangvt** [comment]
Seems I continue to run into issues with this log transformation of the intersection size.  I have noticed that when I log10 or log2 transform my counts, these log values are not reflected in the numbers above the bars, nor in the y axis.  Instead what is output are the total, untransformed counts. While the log transformation is clearly successful (the size of the bars relative to one another reflects this), I would like to be able to exhibit this with the graph axis and bar count labels as well.  Any chance there is a way to do this?

**Comment by JakeConway** [comment]
Hello Andrew, I just pushed this feature to the repo. should be all set to go. I didn't have any data sets large enough to test the log10 scale on

**Comment by AndrewLangvt** [comment]
Thanks for that Jake, definitely will take the log now, but still seems to be some bugs somewhere.  The log values are all rounded to the nearest whole number, no decimal places are retained.  Thus, my plot has multiple "plateaus" and the y-axis doesn't appear to truly have tick marks as my highest intersection size once log transformed is 4.33.  I have included an image to clarify... 

<img width="525" alt="screen shot 2016-11-29 at 7 41 51 pm" src="https://cloud.githubusercontent.com/assets/14237488/20735112/e967a6d0-b66b-11e6-8fc3-0efbc51dd88c.png">

**Comment by JakeConway** [comment]
I've allowed for 2 decimal points when using either log scale. Does that work?

**Comment by AndrewLangvt** [comment]
Thanks Jake, that definitely helps- we're certainly getting there. This dataset seems to be a bit pesky though!  It's now giving me a warning that "Transformation introduced infinite values in continuous y-axis" which I am sure is because I have some instances where there is a single value in a particular intersection.  Is there any way to allow for this and also not adjust the ymin to 0?

<img width="1056" alt="screen shot 2016-11-29 at 7 59 42 pm" src="https://cloud.githubusercontent.com/assets/14237488/20735515/95c35fee-b66e-11e6-9163-eb7c35fb083d.png">

**Comment by JakeConway** [comment]
There is no ymin = 0. To fix the error mentioned above with the NAs, the y axis was adjusted to the following:

`scale_y_continuous(trans = scale_intersections, limits = c(NA, ymax))`

If 0 is inserted in place of NA, then we get an even more broken axis. This may be a bug with the scales package or ggplot2 package

**Comment by AndrewLangvt** [comment]
upon a bit further investigation, those lower counts on the right end of the graph are intersections with low counts (<10), and thus are fractions when log transformed.  Is there no way to have the y axis min be set to zero, or closer to 0 than 1 as it currently stands, yet still handle the NAs?

**Comment by JakeConway** [comment]
Yes, that is the same thing I saw, where the log scale sets the minimum to 1 so any decimal value gets flipped upside down. log10(n < 10) < 1 and log2(n < 2) < 1. I couldn't find a fix to this, but I found: http://stackoverflow.com/questions/9231885/how-can-i-set-axis-ranges-in-ggplot2-when-using-a-log-scale which doesn't look promising.

**Comment by JakeConway** [comment]
Disregard that last comment. I found a fix.

**Comment by JakeConway** [comment]
Pushed fix to repo.

**Comment by AndrewLangvt** [comment]
SUCCESS!! Thanks much Jake, so appreciate your help!

<img width="1034" alt="screen shot 2016-12-01 at 12 06 19 pm" src="https://cloud.githubusercontent.com/assets/14237488/20803859/acaaecee-b7be-11e6-8978-0d36971bd208.png">
