### ISSUE TITLE
Original matrix set order

### ISSUE THREAD

**Issue by moaine** [hms-dbmi/UpSetR#46]
Dear jake,
Congrat for this very nice and useful package ! I did have one question or request if there is a solution of course. I would like to order the final intersection by names. If I'm comparing 2 group with different members and I would like to see all the intersections within the 1st group first , then within the second one and finally between members of different group. UpsetR order the intersections by set size and I can not find any option to chose the order of the intersection by header column as it appear in the matrix for exemple.
I don't know if I was clear and thanks you in advance for your help

**Comment by JakeConway** [comment]
Hello Moaine,
I've just implemented a feature that will allow this when entering the sets using the `sets` parameter. See example 4: https://cran.r-project.org/web/packages/UpSetR/vignettes/basic.usage.html

**Comment by moaine** [comment]
Dear Jake,
Thank you so much for this new feature this will be very helpful.
Many thanks again !
cheers

Moaine El Baidouri

2016-08-02 3:58 GMT+02:00 Jake Conway <notifications@github.com>:

**Comment by moaine** [comment]
Dear Jake,
The new feature worked well for me, however I think that there is a bug in
the set size histogram. In fact it does not correspond to the names of the
of the set. Thank you again for your quick support.

Moaine

2016-08-02 8:25 GMT+02:00 Moaine Elbaidouri <moaine.elbaidouri@gmail.com>:

**Comment by JakeConway** [comment]
Hello Moaine,
If you download the latest version from Github using `devtools::install_github('hms-dbmi/UpSetR')` this should be fixed.

- Jake

**Comment by moaine** [comment]
Many thanks Jake ! it's working now.


2016-08-03 17:55 GMT+02:00 Jake Conway <notifications@github.com>:
