### ISSUE TITLE
Input Data Format

### ISSUE THREAD

**Issue by gk7279** [hms-dbmi/UpSetR#47]
Dear UpSetR team,

Thank you for a great piece of work.

My input file has 7 columns with each column having genenames like this

head input.txt
```
Sample1,Sample2,Sample3,Sample4,Sample5,Sample6,Sample7
uc008vaw.1Rnu11,uc008vaw.1Rnu11,uc012aua.1AB339930,uc012ath.2Rn45s,uc008gfm.1AK197973,uc008gfm.1AK197973,uc012bec.1Mir122a
uc008ztz.1AK212710,uc008ztz.1AK212710,uc008ztz.1AK212710,uc008vaw.1Rnu11,uc008gfl.1AK181808,uc008gfl.1AK181808,uc008yaz.2Alb
uc009phb.3Apoa1,uc008gfl.1AK181808,uc033fml.1Mir8114,uc008ztz.1AK212710,uc012bhe.1Neat1,uc012bhe.1Neat1,uc008vxy.1Errfi1
uc008yaz.2Alb,uc008gfm.1AK197973,uc011zoa.1Mir320,uc008gfl.1AK181808,uc008gfk.1AK148054,uc008gfk.1AK148054,uc008eet.2Ttr
uc007puo.1Hist1h4c,uc011zxb.1Rnu12,uc008vaw.1Rnu11,uc012bhe.1Neat1,uc012bec.1Mir122a,uc008odl.1Pck1,uc009phb.3Apoa1
uc012aua.1AB339930,uc012aua.1AB339930,uc012bty.1Mir2861,uc008gfk.1AK148054,uc008yaz.2Alb,uc012bec.1Mir122a,uc008vxw.1Errfi1

```

But when I read this CSV file with read.csv function in R and issue the upset command, I get an error saying "Error in start_col:end_col : argument of length 0"

Should I transform my input file?

Kindly advice.

Thanks
~G~

**Comment by ngehlenborg** [comment]
Can you please provide sample code that demonstrates what exactly you are doing? That will help us identify the problem.

**Comment by gk7279** [comment]
I am sorry. I figured out that I had to transform the data into 0s and 1s. I did that.

Now I ran into a strange issue. I have more than 21000 common genes across all 7 sets. But the x axis is not showing all of them. Is there a parameter that I am missing so that I can see all combinations on the x-axis?

Here is the command I am using

Actually, my input.csv is like this
```
Name,SET1,SET2,SET3,SET4,SET5,SET6,SET7
uc007aey.1Sox17,1,1,1,1,0,1,1
uc007aez.2Sox17,1,1,1,1,1,1,0
uc007afa.2Sox17,1,1,1,1,1,1,0
uc007afb.2Sox17,1,1,1,1,1,1,0
uc007afc.2Sox17,1,1,1,1,1,1,0
uc007afd.3Mrpl15,1,1,1,1,1,1,1
uc007afe.3Mrpl15,1,1,1,1,1,1,1
uc007aff.3Mrpl15,1,1,1,1,1,1,1
uc007afg.1Lypla1,1,1,1,1,1,1,1
```


Here is the script I am using to make the plot
```
library(UpSetR)
data=read.csv("input.csv",header=T,sep=",")
upset(data,nsets=7)
```

Thanks

**Comment by ngehlenborg** [comment]
That's looking better. I assume you are looking for the `empty.intersections` flag:

```R
library(UpSetR)
data=read.csv("input.csv", header=T, sep=",")
upset(data, nsets=7, empty.intersections=TRUE)
```

That will show all possible combinations of sets (i.e. intersections) including those of size 0.

**Comment by gk7279** [comment]
Thank you. 

When I use order.by="freq", the common genes from all 7 samples comes in. But the other ones are gone. The x-axis is not carrying all combinations. It only shows 40combinations.

**Comment by ngehlenborg** [comment]
By default UpSetR only plots up to 40 intersections. This limit is controlled via the `nintersects` parameter. For 7 sets you should set it to a value of `2^7`or greater if you want to see all intersections.

**Comment by ngehlenborg** [comment]
Closing this issue because it no longer related to the original question. @gk7279 - please open a new issue if the need arises.

**Comment by JakeConway** [comment]
if you don't want to take the time to generate the binary columns, you could try the `fromExpression()` input form seen in example 1 here: 
https://cran.r-project.org/web/packages/UpSetR/vignettes/basic.usage.html
