### ISSUE TITLE
Modify default behavior to show more than 40 intersections?

### ISSUE THREAD

**Issue by ngehlenborg** [hms-dbmi/UpSetR#48]
Currently the `nintersect` parameter limits the number of intersections shown by default to 40.

Should we show all sets  by default?

**Comment by JakeConway** [comment]
it all depends on the number of sets. if the default is 5 sets (which it currently is), the max number of intersections is 31. If the default is 6 sets, the max number of intersections is 63

**Comment by ngehlenborg** [comment]
It depends a bit on the answer to #49 - if there is a way to deactivate this limit (e.g. using `nintersect=NA`), then that could be the default instead of `40`. Although I see the issues that can arise, like someone plugging in dozens of sets, resulting in `2^dozens`intersections ...

**Comment by ngehlenborg** [comment]
For now the solution to #49 addresses this to some extent (easier to show all intersections now) but let's leave the default behavior as is and maybe change it to show all intersections by default when we have a major release (2.x.x).

**Comment by JakeConway** [comment]
Decided after discussion with @ngehlenborg not to address at this point
