### ISSUE TITLE
keep.order only moves labels on sets, the bars don't change

### ISSUE THREAD

**Issue by ryanrichholt** [hms-dbmi/UpSetR#51]
Code to replicate:

    library(UpSetR)
    movies <- read.csv( system.file("extdata", "movies.csv", package = "UpSetR"), header=TRUE, sep=";" )
    UpSetR::upset(movies, keep.order = TRUE, sets = c("Drama", "Thriller", "Action"))
    UpSetR::upset(movies, keep.order = TRUE, sets = c("Thriller", "Drama", "Action"))

In the first plot, "Drama" is the largest set in the barplot on the left. In the second plot, "Thriller" is the largest set.

**Comment by ngehlenborg** [comment]
Thanks for reporting this bug. @JakeConway - can you have a look into this? 

```R
UpSetR::upset(movies, keep.order = TRUE, sets = c("Drama", "Thriller", "Action"))
```
![rplot01](https://cloud.githubusercontent.com/assets/1216518/18138815/8e77e4b4-6f7c-11e6-84f6-b388f08c2b73.png)

```R
UpSetR::upset(movies, keep.order = TRUE, sets = c("Thriller", "Drama", "Action"))
```
![rplot08](https://cloud.githubusercontent.com/assets/1216518/18138814/8e7621ec-6f7c-11e6-8a16-cf613edccc1c.png)

**Comment by JakeConway** [comment]
Hello Ryan,

Please see https://github.com/hms-dbmi/UpSetR/issues/46

I haven't submitted an updated version of the package to CRAN due to their submission policy.

**Comment by ryanrichholt** [comment]
Thanks Jake, installed the latest version with devtools::install_github('hms-dbmi/UpSetR')
and the problem is resolved.
