### ISSUE TITLE
Using existing dataframe with UpSetR

### ISSUE THREAD

**Issue by GeoMicroSoares** [hms-dbmi/UpSetR#53]
Hello there,

Trying to use a dataframe in R I generated from an abundance matrix t, I keep getting this error when using UpSetR:

`Error in sort.list(y) : 'x' must be atomic for 'sort.list'
Have you called 'sort' on a list?`

Here's the beggining of the said dataframe:

          OTU_IDS Amphibolite Basalt Coal Coal-Upper Dolomite Hematite_Granite High-calcite_clay mica_schist
      1 KC442817.1.1478           1      0    0          0        0                0                 0
      2 JX222276.1.1475           0      1    0          0        0                0                 0
      3 HQ218444.1.1344           0      0    0          0        0                0                 1
      4 DQ517124.1.1380           0      0    0          0        0                0                 0
      5 KF827260.1.1400           0      1    0          0        0                0                 0
      6 EF125930.1.1497           0      0    0          0        0                0                 0

Any ideas?

Thanks in advance.

André

**Comment by JakeConway** [comment]
could you send me a small snippet of the data frame so I could test it? It may have something to do with the types of your columns.

**Comment by GeoMicroSoares** [comment]
Here's a quick csv output from the table I'm using:
[final_MADS_upsetr.txt](https://github.com/hms-dbmi/UpSetR/files/511218/final_MADS_upsetr.txt)

**Comment by JakeConway** [comment]
![rplot](https://cloud.githubusercontent.com/assets/12614369/19115299/6e924f1c-8adf-11e6-96d9-d2af757dc86f.png)

I got this UpSet plot when using your data. I just made sure that the type of each binary column was an integer.

**Comment by GeoMicroSoares** [comment]
looks good! any tips on how to do that?

**Comment by JakeConway** [comment]
`for(i in 2:ncol(data)){
     data[ , i] <- as.integer(data[ , i])
}`

**Comment by GeoMicroSoares** [comment]
With this I get a binary data frame of 1s and 2s and then 
`upset(data)`
`Error in start_col:end_col : argument of length 0`

**Comment by JakeConway** [comment]
`for(i in 2:ncol(data)){
  data[ , i] <- as.integer(data[ , i])
  for(j in 1:nrow(data)){
    data[ j, i] <- data[j, i]-1
  }
}`

**Comment by GeoMicroSoares** [comment]
Thanks, I now see the graph but it only shows data from five columns (same as yours, but not showing Tuff, for example). How can I fix this up?
