### ISSUE TITLE
not compatible with current grid release

### ISSUE THREAD

**Issue by GuangchuangYu** [hms-dbmi/UpSetR#54]
```
> mutations <- read.csv( system.file("extdata", "mutations.csv", package = "UpSetR"), header=T, sep = ",")
> upset(mutations, sets = c("PTEN", "TP53", "EGFR", "PIK3R1", "RB1"), sets.bar.color = "#56B4E9",
+ order.by = "freq", empty.intersections = "on")
Error in unit(rep(yp, n), "npc") : 'x' and 'units' must have length > 0
> packageVersion("grid")
[1] ‘3.3.1’
```

please fix it.

**Comment by ngehlenborg** [comment]
@GuangchuangYu: which UpSetR package version are you using? I am unable to reproduce this with 1.2.4 (and 1.2.3).

**Comment by JakeConway** [comment]
The error you received is foreign to UpSetR. "npc" units are not used in the package. Both me and @ngehlenborg  are able to produce the plot.

**Comment by ngehlenborg** [comment]
@GuangchuangYu: `unit(rep(yp, n), "npc")` appears to be code in ggplot2 (https://github.com/hadley/ggplot2/blob/master/R/margins.R#L62). Did you make any changes to the margins?

**Comment by GuangchuangYu** [comment]
I didn't change the margins. I have updated ggplot2 two days ago. And now I re-run the code again, it draw the figure successfully.

It maybe an issue of previous version of ggplot2.
