### ISSUE TITLE
intersection expression input format

### ISSUE THREAD

**Issue by ngehlenborg** [hms-dbmi/UpSetR#55]
The basic usage vignette at https://cran.r-project.org/web/packages/UpSetR/vignettes/basic.usage.html shows the wrong quote character (`) for the intersection expression input:

![screen shot 2016-10-07 at 2 18 28 am](https://cloud.githubusercontent.com/assets/1216518/19180533/79cdc662-8c34-11e6-8aad-13408af9aa04.png)

The Markdown file at https://github.com/hms-dbmi/UpSetR/blob/master/vignettes/basic.usage.Rmd uses the correct one ("):

![screen shot 2016-10-07 at 2 18 41 am](https://cloud.githubusercontent.com/assets/1216518/19180537/7e1fafe6-8c34-11e6-9bb3-972c1e790282.png)

Has the vignette not been updated or is this a problem with how the vignettes are built?

**Comment by JakeConway** [comment]
It's unlikely that it hasnt been updated on CRAN. In my local Rproject I have double quotes, and the vignette was last updated prior to the last submission.

**Comment by JakeConway** [comment]
It seems to be the vignette build that is changing " " to ` `
