### ISSUE TITLE
Naming of queries?

### ISSUE THREAD

**Issue by steichten** [hms-dbmi/UpSetR#57]
Is there a way to name each query to be passed to the query.legend? 

The names 'Query1','Query2', etc are not all that helpful to show in a legend. Perhaps I'm missing it in the docs if that feature is already present. Maybe an optional 'query.name' argument for each query list?

**Comment by JakeConway** [comment]
There currently isn't a way to name each query. It was supposed to be implemented, but was most likely forgotten about. I will add this feature to the package. Thanks for the catch!

**Comment by JakeConway** [comment]
This is now a feature. An example can be found here: https://github.com/hms-dbmi/UpSetR/blob/master/vignettes/queries.Rmd
