### ISSUE TITLE
Specifying intersections of degree 1

### ISSUE THREAD

**Issue by natbprice** [hms-dbmi/UpSetR#61]
The "intersections" argument is described as:

Specific intersections to include in plot entered as a list of lists. Ex: list(list("Set name1", "Set name2"), list("Set name1", "Set name3")). If data is entered into this parameter the only data shown on the UpSet plot will be the specific intersections listed.

Is it possible to include intersections of degree 1? I can specify intersections of degree 2 or higher, but I can't figure out the syntax for including a single set (i.e. degree 1). It would be nice to have this functionality to fully control what intersections are plotted.

**Comment by JakeConway** [comment]
Thanks for the suggestion! I will try to have this implemented later today.

**Comment by JakeConway** [comment]
This feature is already implemented. 

See `upset(movies, intersections = list(list("Drama", "Comedy"), list("Drama")))` 

and

`
#Default order in upset is by degree then freq`
`#Use order.by parameter and decreasing parameter to switch how these are ordered`
`upset(movies, nsets=17, nintersects = 17)`


Regarding the first option where you can type each set individually, you can choose whether or not to keep the order you entered the list by using the `keep.order` parameter. If set to TRUE, it will keep the order entered and wont try to order it by degree or frequency.

**Comment by natbprice** [comment]
Thanks for your fast reply. The following works

`upset(movies, intersections = list(list("Drama", "Comedy")))`

but 

`upset(movies, intersections = list(list("Drama")))`

does not work.
