### ISSUE TITLE
unique and then intersections

### ISSUE THREAD

**Issue by Indigofera** [hms-dbmi/UpSetR#65]
Hi, I have a data which has 10 sets. And I want to show first unique ones and then intersections for these 10 sets in UpSet plot. But I did not find a way. Is it possible? Or how to fix this figure?

**Comment by JakeConway** [comment]
You can use the `group.by` parameter to group by `degree` instead of the default `sets`

**Comment by Indigofera** [comment]
sorry, but it did not work, too

**Comment by JakeConway** [comment]
see: 
```R
upset(movies, order.by = 'degree', decreasing = F)
```

**Comment by Indigofera** [comment]
Also , I used the order.by = c("freq", "degree"). It worked for unique ones but I have intersections for 10 sets which I did not see for this time.

**Comment by JakeConway** [comment]
you can increase the number of sets and intersections you see using `nsets` and `nintersections`

**Comment by Indigofera** [comment]
Is there any way after unique ones, I can start with intersection which overlap for 10 sets and then decreasing?

**Comment by JakeConway** [comment]
currently there isn't a way to do that

**Comment by Indigofera** [comment]
ok thank you so much
