### ISSUE TITLE
intersection size filter?

### ISSUE THREAD

**Issue by sonicfray** [hms-dbmi/UpSetR#67]
Is there a way to filter out any small intersections?  I don't want to see for example intersections smaller than 10.

**Comment by JakeConway** [comment]
You could try ordering by degree then frequency, then adjusting `nintersections` to cut off the intersections that are < 10.

```R
#order by degree then freq. can adjust "decreasing" parameter to change direction of order
upset(movies, order.by = c("degree", "freq"))
```

**Comment by sonicfray** [comment]
very helpful- thanks that works as an indirect method, but it would be nice to have a direct way to also group by sets and also have a minimum intersection size applied, especially when you're looking at large numbers of intersections and variables and doing exploratory analysis and you're more focused on those with largest intersections.
