### ISSUE TITLE
Formatting value labels

### ISSUE THREAD

**Issue by geotheory** [hms-dbmi/UpSetR#68]
Awesome library guys. One request - I think the scientific number formatting (e.g. `6e+05`) is going to make this less easy for some of my more senior colleagues to interpret.  Is it possible to add an option in line with ggplot `labels = comma` approach?

I have tried looking into the underlying code but confess I can't figure out where the relevant bit(s) are.

**Comment by JakeConway** [comment]
The ggplot to make the set size bar plot is in `SizeBar.R` and the ggplot to make the intersection size bar plot is in `MainBar.R`. Let me know if adding `labels = comma` doesn't work.
