### ISSUE TITLE
Intersection size do not match data

### ISSUE THREAD

**Issue by maxibor** [hms-dbmi/UpSetR#72]
Hi @ngehlenborg , @JakeConway  and the other creators of UpSet,
First of all, thanks for your work I really like this visualization ! 
However I'm doing an UpSet Plot on my data, but the intersection size on the plot is really different from the real one : 

Here are my data (**df**)

| "camera" | "globaltest" | "gsva" | "ssgsea" | "zscore" | "plage" | "ora" | "padog" | "roast" | "safe" | 
|----------|--------------|--------|----------|----------|---------|-------|---------|---------|--------| 
| 0        | 1            | 1      | 1        | 1        | 1       | 0     | 1       | 1       | 1      | 
| 0        | 1            | 1      | 1        | 1        | 1       | 0     | 1       | 1       | 1      | 
| 0        | 1            | 1      | 1        | 1        | 1       | 0     | 1       | 1       | 1      | 
| 0        | 1            | 1      | 1        | 1        | 1       | 0     | 1       | 1       | 1      | 
| 0        | 1            | 1      | 1        | 1        | 1       | 0     | 1       | 1       | 1      | 
| 0        | 1            | 1      | 1        | 1        | 1       | 0     | 1       | 1       | 0      | 
| 0        | 1            | 1      | 1        | 1        | 1       | 0     | 1       | 1       | 0      | 
| 0        | 1            | 1      | 1        | 1        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 1      | 1        | 1        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 1      | 1        | 1        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 1      | 1        | 1        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 1      | 1        | 1        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 1      | 1        | 1        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 1      | 1        | 1        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 0      | 1        | 0        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 0      | 1        | 0        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 0      | 1        | 0        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 0      | 1        | 0        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 0      | 1        | 0        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 0      | 1        | 0        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 1       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 0       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 0       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 0       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 0       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 0       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 0       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 0       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 0       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 0       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 0       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 0       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 0       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 0       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 0       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 0       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 0       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 0       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 0       | 0      | 
| 0        | 1            | 0      | 0        | 0        | 1       | 0     | 0       | 0       | 0      | 
| 0        | 0            | 0      | 0        | 0        | 1       | 0     | 0       | 0       | 0      | 

Here is the code I'm using

```{r}
upset(as.data.frame(df), nsets = 10, nintersects = NA)
```
And here is the Upset Plot produced. The maximum intersection size in **19** where it should be **49** (column "globaltest" vs column "plage")

![upsetplot](https://cloud.githubusercontent.com/assets/8630837/24760224/52eed728-1ae8-11e7-9308-3a1099f18a7e.png)

**Session info :**

```
R version 3.3.3 (2017-03-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8    LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] UpSetR_1.3.3               safe_3.14.0                SparseM_1.76               AnnotationDbi_1.36.2      
 [5] PADOG_1.16.0               KEGGdzPathwaysGEO_1.12.0   GSVA_1.22.4                globaltest_5.28.0         
 [9] survival_2.41-3            gage_2.24.0                limma_3.30.13              pd.mogene.1.0.st.v1_3.14.1
[13] oligo_1.38.0               DBI_0.6-1                  RSQLite_1.1-2              Biostrings_2.42.1         
[17] XVector_0.14.1             IRanges_2.8.2              S4Vectors_0.12.2           Biobase_2.34.0            
[21] oligoClasses_1.36.0        BiocGenerics_0.20.0       

loaded via a namespace (and not attached):
 [1] httr_1.2.1                 jsonlite_1.3               splines_3.3.3              foreach_1.4.3             
 [5] hgu133a.db_3.2.3           doRNG_1.6                  yaml_2.1.14                backports_1.0.5           
 [9] lattice_0.20-34            digest_0.6.12              GenomicRanges_1.26.4       colorspace_1.3-2          
[13] htmltools_0.3.5            preprocessCore_1.36.0      Matrix_1.2-8               plyr_1.8.4                
[17] GSEABase_1.36.0            XML_3.98-1.6               affxparser_1.46.0          zlibbioc_1.20.0           
[21] xtable_1.8-2               KEGG.db_3.2.3              scales_0.4.1               affyio_1.44.0             
[25] ff_2.2-13                  tibble_1.3.0               annotate_1.52.1            KEGGREST_1.14.1           
[29] pkgmaker_0.22              ggplot2_2.2.1              SummarizedExperiment_1.4.0 lazyeval_0.2.0            
[33] magrittr_1.5               memoise_1.0.0              evaluate_0.10              nlme_3.1-131              
[37] GSA_1.03                   graph_1.52.0               BiocInstaller_1.24.0       tools_3.3.3               
[41] registry_0.3               stringr_1.2.0              munsell_0.4.3              rngtools_1.2.4            
[45] GenomeInfoDb_1.10.3        grid_3.3.3                 RCurl_1.95-4.8             iterators_1.0.8           
[49] labeling_0.3               bitops_1.0-6               base64enc_0.1-3            rmarkdown_1.4             
[53] gtable_0.2.0               codetools_0.2-15           R6_2.2.0                   gridExtra_2.2.1           
[57] knitr_1.15.1               bit_1.1-12                 hgu133plus2.db_3.2.3       rprojroot_1.2             
[61] stringi_1.1.3              Rcpp_0.12.10               png_0.1-7        
```

**Comment by JakeConway** [comment]
Is it possible to share your dataset?

**Comment by ngehlenborg** [comment]
The numbers in UpSet are correct. Each bar in UpSet corresponds to an intersection, but the 49 that you are quoting is the total number of elements in the "globaltest" set. Since that set is intersecting with other sets, you'd need to add up the elements in all intersections that "globaltest" is part of, which are all but the first intersection in your sample plot above. Adding up the sizes the size of those intersections, gives you all elements in "globaltest": 19 + 10 + 6 + 7 + 2 + 5 = 49

**Comment by maxibor** [comment]
Here is the [csv file](https://github.com/hms-dbmi/UpSetR/files/905048/df.csv.zip) (compressed to accept GitHub file format restrictions, but it's only 1.1 Ko).  

However I'm not sure to follow you @ngehlenborg : I should have an intersection size of 49 between "globaltest" and "plage" : I have 49 features (lines) in common between "globaltest" and "plage" ("globaltest" has 49 **1** and "plage" has 50 **1**).

**Comment by JakeConway** [comment]
When plotting we only consider the elements in the sets specified. In the case of the first plot this is between PTEN and TP53. Thus, some of the elements in the first plot that are shown in PTEN alone could also be in EGFR. Since we aren't considering EGFR, they are just shown in the 1-way intersection of PTEN. When including EGFR in the second plot, those elements will now be included in the 2-way intersection between PTEN and EGFR, which is one reasons why there is a decrease in the 1-way intersection size of PTEN. Also, notice how the number of elements included in PTEN doesn't change (87 in both).

**Comment by aayushraman** [comment]
Thanks, this makes sense. However, is it possible to show specific interactions as @maxibor mentioned ?

**Comment by Eugeniia** [comment]
I have the same problem. I have 6 sets. When plotting 5 sets, the number of elements plotted for each set match with the number of elements in each set. But when I trying to plot 6 sets, the number of elements plotted for each set is wrong, moreover, it doesn't show the intersection between all 6 sets but it exists. I checked this with python command:

python3 -c 'import sys;print("".join(sorted(set.intersection(*[set(open(a).readlines()) for a in sys.argv[1:]]))))' A.txt B.txt C.txt D.txt E.txt F.txt > ABCDEF_overlap.txt

**Comment by Eugeniia** [comment]
Is there a maximum number of intersects to plot? In my case, I already have more than 35 for 6 sets. Maybe this is the problem?

**Comment by jtrosenthal** [comment]
I have been running into this issue myself - the way that UpSetR calculates set intersection size is not intuitive. Until the UpSetR team adds support for this, my workaround was to use the ComplexHeatmap package (see [here](https://jokergoo.github.io/ComplexHeatmap-reference/book/upset-plot.html#upset-mode) for the section detailing different modes for calculating set intersection size. I think "intersect" is what you are looking for). Hopefully this feature will be added in a future version of UpSetR!

**Comment by mehmetdayi** [comment]
Hi all,
I have the same problem.
This is the code that I am running:

`upset(fromList(mydata), nsets = 7)`

This is part of my data

Name	A	B	C	D	E	F	G
OG0000000	0	2	1	9	1	5	17
OG0000001	0	0	0	5	0	0	5
OG0000002	0	0	0	5	0	2	32
OG0000003	0	0	0	14	0	0	16
OG0000004	0	0	0	5	0	2	14
OG0000005	0	0	0	7	0	0	9
OG0000006	0	0	0	10	0	0	7
OG0000007	0	0	0	11	0	0	8
OG0000008	0	0	0	0	0	0	2
OG0000009	1	1	1	6	1	2	7
OG0000010	0	0	0	7	0	2	4
OG0000011	0	0	0	4	0	2	8
OG0000012	0	0	0	4	0	1	11
OG0000013	0	0	0	3	0	0	5
OG0000014	0	1	1	2	0	1	5
OG0000015	1	0	0	3	0	2	4
OG0000016	0	0	0	4	0	1	5
OG0000017	0	0	0	3	0	2	5
OG0000018	1	1	1	3	1	3	3

**Comment by lycuser** [comment]
> I have been running into this issue myself. Basically, there are a few different ways to calculate set intersection size, shown in the image below. UpSetR uses the "distinct" mode, while "intersect" mode may be what the user expects when reading one of these plots.
> 
> As far as I can tell, UpSetR does not support "intersect" mode. Until the UpSetR team adds support for this mode, my workaround was to use the ComplexHeatmap package which allows the user to choose which mode to use.
> 
> Hopefully this feature will be added in a future version of UpSetR!
> 
> ![image](https://user-images.githubusercontent.com/34822893/76452255-34845f00-63a7-11ea-8bd4-f7e0c25110fe.png)

Hi there! do you know of a function that allows you to look at what is distinctly shared between data tables/data frames? I am having a hard time doing this and want to make a table that shows the distinct intersections that UpSetR is plotting.
