### ISSUE TITLE
X-axis of intersection size barplot not visible.

### ISSUE THREAD

**Issue by royfrancis** [hms-dbmi/UpSetR#73]
Numbers displayed above the barplot are not clearly visible when value is below 3. I suppose you could add a limit. Issue marked in red below.

![upset-genes-testes](https://cloud.githubusercontent.com/assets/5083500/24870941/4c058da2-1e18-11e7-9e1e-d2976c44fb4c.png)

<details>
<summary>Session Info</summary>

R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252  

UpSetR_1.3.3

</details>

**Comment by aayushraman** [comment]
use `text.scale` argument to 1.5 or 2.

**Comment by royfrancis** [comment]
To bring this issue up again, it not just a matter of the text missing. The lower portion including x-axis of the upper barplot is missing. As you can see, there is no 0 on the y-axis.
