### ISSUE TITLE
UpsetR -- Comparison of one dataset to the rest

### ISSUE THREAD

**Issue by aayushraman** [hms-dbmi/UpSetR#75]
Hi Jake and Nil,

I would like to say thanks to you guys for coming up with a amazing package. I have a question regarding the use of UpSetR. I have a dataset (https://www.dropbox.com/s/rm3rwm8uf67lb5y/ExampleDataset.txt?dl=0) with first column as gene name and other 9 column (A-I) as list of studies. It is a binary dataset with values as 0 and 1. I am interested in comparing A to B; A to C, A to D and so on. To do this, I run the following command : 

``
upset(dat.all, intersections = list(list("A"), list("A", "B"), list("A", "C"), list("A", "D"), 
    list("A", "E"), list("A", "F"), list("A", "G"), list("A", "H"), 
    list("A", "I")), main.bar.color = "black", mb.ratio = c(0.6,0.4), text.scale = 1.5, 
    queries = list(list(query = intersects, params = list("A"), active = T)))
`` 

I get the following plot: 
![rplot](https://cloud.githubusercontent.com/assets/4062603/24934839/c028cc50-1ee3-11e7-8006-b79dfea76726.png)

However, when you run the number on the top of the bar graph looks off when you run follwoing commands: 

``` 
sum(dat.all$A == 1 & dat.all$F == 1) ## on bar graphs it shows 150 but actually, it is 251
sum(dat.all$A == 1 & dat.all$B == 1) ## on bar graphs it shows 33 but actually, it is 131
sum(dat.all$A == 1 & dat.all$I == 1) ## on bar graph it shows 0 but actually, it is 5
```

I tried looking for the argument in the function that gives me actual numbers with the comparison but I didn't find one. Is it possible to do it ?

Thanks,
-Ar

**Comment by JianWang2016** [comment]
I could be wrong but I think the numbers on the bar graphs are correct.  251 you referred to includes not just A==1 & F==1, it could also include B==1 etc.
