### ISSUE TITLE
Erron in reading data

### ISSUE THREAD

**Issue by phil-gusev** [hms-dbmi/UpSetR#77]
data file:
id	chimp	cow	human	macaque	mouse	naked_mole_rat	rat
3	6	44	103	21	21	1	6
R code:
test<-read.csv("./test.txt",sep = "\t")
upset(test,sets=c("chimp",	"cow",	"human",	"macaque",	"mouse",	"naked_mole_rat",	"rat"))
Error:
Error in `[.data.frame`(data, , start_col:end_col) : 
  undefined columns selected

If the data file:
id	chimp	cow	human	macaque	mouse	naked_mole_rat	rat
1	2	0	272	1	0	0	0
than no error occures.
Could you help me what is wrong?

**Comment by JakeConway** [comment]
The inclusion of an element in a set should be encoded in binary. What do the numbers 3, 6, 44, 103, 21, 21, 1, 6 signify?

**Comment by phil-gusev** [comment]
I'm working on finding orthologous groups among selected species.
Each row represents a group of genes, practically it is a set of counted of genes of a particular spice in the group.

With some subsets of rows with values not equal to 1 or 0 (e.g. 2 or 272 in the last example) the package works fine.

**Comment by brooksph** [comment]
@JakeConway Awesome tool! I can't find a reference to having the data in binary format for in documentation. Sorry if I missed it. I was little confused initially after moving over from pyupset where the data can be in non-binary formats. Sticking a short note somewhere in the docs might save some folks a little head banging.
