### ISSUE TITLE
Bug: Set names and set size bars do not align

### ISSUE THREAD

**Issue by jananiravi** [hms-dbmi/UpSetR#88]
I find that the set size bars and the corresponding set names do not align upon addition of attribute plots. The bars seem to be creeping into the main plot area. I do not encounter this problem when the upset panel is being plotted by itself.

Please see the example below:
![image](https://user-images.githubusercontent.com/8397074/29143451-3b427a7e-7d23-11e7-8912-9c2aa9f62852.png)

**Comment by JakeConway** [comment]
Do you see this same issue when running the examples in the upset function help page (`?UpSetR::upset`)
