### ISSUE TITLE
How to color the lines and bar according to section size?

### ISSUE THREAD

**Issue by Zefeng-Wu** [hms-dbmi/UpSetR#89]
I want to visualize the section of 7 data set,  and i want to highlight the sections (linked lines between circles) and the bar with section size larger than specific number. I don't known how to write the codes.

### my code ###
upset(fromList(listInput),nsets = 7,order.by =  "freq",nintersects = NA)

**Comment by JakeConway** [comment]
See the queries vignette for examples on how to color specific intersections either manually or by your own custom function. https://cran.r-project.org/web/packages/UpSetR/vignettes/queries.html
