### ISSUE TITLE
Specifying intersections should check names

### ISSUE THREAD

**Issue by ghost** [hms-dbmi/UpSetR#93]
Hi,
I stumbled across the problem that specifying intersections via the `intersections=` parameter may fail if the labels of the input datasets contain characters like ` - `. The problem seems to be this call
```R
data <- count(data[keep])
```
in line 10 of `Specific.intersections.R` as the returned data frame contains renamed, i.e., syntactically valid, column names (e.g.: `A-up` and `A-down` would be renamed to `A.up` and `A.down`). The following access by name `x <- x[which(rowSums(x[temp_sets]) == length(temp_sets)), ]` in the `lapply` call then fails due to undefined column names. It would improve the usability of the package if the dataset labels would be checked to avoid problems in downstream function calls.

Also, by eyeballing, I would assume that line 3 `sets <- names(data[c(first.col:last.col)]) ` will fail if some columns are removed when limiting to setting specific intersections, as the parameters `first.col` and `last.col` are initialized before checking the wanted intersections (see lines 135-143 in `upsetR`).

Best,
Peter

**Comment by egenomics** [comment]
Same problem here

**Comment by MeHelmy** [comment]
I have the same issue, the dataframe column names are valid no `_` or` -` or `.` but I have this error:
```
Error in `$<-.data.frame`(`*tmp*`, "freq", value = 8782L) : 
  replacement has 1 row, data has 0
```

Package UpSetR version 1.4.0

**Comment by zx8754** [comment]
@MeHelmy after 2 years, someone with the same issue. Maybe the solution is to use nintersects, see: https://stackoverflow.com/a/74530164/680068

**Comment by Neato-Nick** [comment]
I had a similar error in my dataset and Google led me here
```
Error in `$<-.data.frame`(`*tmp*`, "freq", value = 9L) : 
replacement has 1 row, data has 0
```
The SO answer linked by @zx8754 solved my error. `nintersects =` needs to be set high enough to include the queried intersection. If the queried intersection would not be displayed, `upset` produces the "replacement has 1 row, data has 0" error.
